// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.sample

object PersonProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq.empty
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      com.sample.Person
    )
  private lazy val ProtoBytes: Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """ChNwZXJzb24vcGVyc29uLnByb3RvEgxzY2FsYXBiLmRvY3Mi2QIKBlBlcnNvbhIdCgRuYW1lGAEgASgJQgniPwYSBG5hbWVSB
  G5hbWUSGgoDYWdlGAIgASgFQgjiPwUSA2FnZVIDYWdlEkoKCWFkZHJlc3NlcxgDIAMoCzIcLnNjYWxhcGIuZG9jcy5QZXJzb24uQ
  WRkcmVzc0IO4j8LEglhZGRyZXNzZXNSCWFkZHJlc3NlcxqkAQoHQWRkcmVzcxJVCgxhZGRyZXNzX3R5cGUYASABKA4yIC5zY2FsY
  XBiLmRvY3MuUGVyc29uLkFkZHJlc3NUeXBlQhDiPw0SC2FkZHJlc3NUeXBlUgthZGRyZXNzVHlwZRIjCgZzdHJlZXQYAiABKAlCC
  +I/CBIGc3RyZWV0UgZzdHJlZXQSHQoEY2l0eRgDIAEoCUIJ4j8GEgRjaXR5UgRjaXR5IiEKC0FkZHJlc3NUeXBlEggKBEhPTUUQA
  BIICgRXT1JLEAFiBnByb3RvMw=="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, Array(
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}
